### ISSUE TITLE
n3dr not updated

### ISSUE THREAD

**Issue by 030** [digitalcoyote/chocolatey-packages#15]
Could the auto bot be updated so that the latest package of n3dr will become available on chocolatey?

**Comment by digitalcoyote** [comment]
Thank you for catching this. Unfortunately outside of work for the next day or so I'll be repairing a fence so my dog doesn't get out again (he found out which boards were weak). 

In the meantime, I'd accept a pull request if you want take a shot at it (probably a regex issue). Otherwise I'll get to this ASAP.

**Comment by 030** [comment]
@digitalcoyote I will have a look.

**Comment by digitalcoyote** [comment]
I found some downtime during a meeting. It's not just a regex issue. I'll be manually pushing 6.0.1 and I'll try to get this corrected soon.

**Comment by gfinesch** [comment]
Thank you for your support!
