### ISSUE TITLE
oh-my-posh

### ISSUE THREAD

**Issue by xmha97** [digitalcoyote/chocolatey-packages#34]
Chocolate packages will be installed for all users (not the current user)
I just noticed that the oh-my-posh package is installed by default only for the current user.
This is not good, since chocolate packages are installed only once, if one user installs a package, another user can not install it.

Maybe this change will solve this problem:
```
...
$PackageParameters = Get-PackageParameters

### PARAMETERS
If ($PackageParameters.CurrentUser) {
    $silentArgs = "$silentArgs /CURRENTUSER"
} Else {
    $silentArgs = "$silentArgs /ALLUSERS"
}
...
```
Thanks

**Comment by digitalcoyote** [comment]
As second user should be able to reinstall oh-my-posh with the parameter. I'm wary of changing a parameter that was added for another user since it could break existing scripts and it would be changing the default that was originally in the package. 

That said, this is the second time someone has asked for this as the default and I think most users are the only user of their machine (so it shouldn't affect them anyway).

If you want to submit that as a PR, I'd be willing to pll it in. It needs to have the parameter documented on the nuspec as well. I can see about making the change, but it may take a few days for me to get to it.

**Comment by digitalcoyote** [comment]
Looking at this tonight. Hopefully I can get it tested and pushed up for the next oh-my-posh release

**Comment by digitalcoyote** [comment]
Pushed this up a moment ago and it will appear in versions after 8.5.0

For those who may be directed here from the description on the package,
Although the profile modified is generally the one that is used to install/update oh-my-posh, scripted deployments are likely to need an administrator to be able to install for other users. Because of this the default was changed from CURRENTUSER to ALLUSERS for the install.

**Comment by xmha97** [comment]
Thanks <3
